# Generated by Django 4.2 on 2026-04-28 17:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('pickup_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('pickup_address', models.TextField()),
                ('destination_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('destination_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('destination_address', models.TextField()),
                ('route_polyline', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('searching', 'Searching'), ('driver_assigned', 'Driver Assigned'), ('driver_arriving', 'Driver Arriving'), ('otp_verified', 'OTP Verified'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='searching', max_length=20)),
                ('otp_code', models.CharField(blank=True, max_length=60, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('pricing_breakdown', models.JSONField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('driver_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('driver_arrived_at', models.DateTimeField(blank=True, null=True)),
                ('ride_started_at', models.DateTimeField(blank=True, null=True)),
                ('ride_completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('user', 'User'), ('driver', 'Driver'), ('admin', 'Admin')], max_length=10, null=True)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('driver_rating', models.IntegerField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('driver_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='users.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='users.user')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.vehicle')),
            ],
            options={
                'db_table': 'rides',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RideDriverRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_requests', to='rides.ride')),
            ],
            options={
                'db_table': 'ride_driver_requests',
                'unique_together': {('ride', 'driver')},
            },
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['user'], name='rides_user_id_2b5a93_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver'], name='rides_driver__8fdcf2_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status'], name='rides_status_376a74_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['-requested_at'], name='rides_request_01e9aa_idx'),
        ),
    ]
